### ISSUE TITLE
"TypeError: unsupported operand" when saving pages

### ISSUE THREAD

**Issue by tony2nite** [skirsdeda/wagtail-translation#1]
On a clean install of Wagtail, when saving I get a TypeError in `set_url_path `. 

Both `url_path_en` and `url_path_de` are 'None' as they come into this function which is causing this error. Even if I patch the string conversion of None to avoid the error, I get the text 'None' coming through as part of the generated URLs.

```
# Python 3.5.1
Request Method:	POST
Request URL:	http://127.0.0.1:8000/admin/pages/add/home/projectpage/2/
Django Version:	1.10.5
Exception Type:	TypeError
Exception Value:	
unsupported operand type(s) for +: 'NoneType' and 'str'
Exception Location:	/Users/user/.virtualenvs/wagtail/lib/python3.5/site-packages/wagtail_translation/page_patch.py in set_url_path, line 42
```

**Comment by skirsdeda** [comment]
@tony2nite Got it. Fix coming up.

**Comment by skirsdeda** [comment]
@tony2nite just update wagtail-translation and run migrate. The bug should be gone.

**Comment by tony2nite** [comment]
Great. Works.

Note I had to pip install like this:

```pip install -e git+https://github.com/skirsdeda/wagtail-translation.git#egg=wagtail-translation```

Without the development version the 'migrations' folder wasn't being pulled down. Google says it might be because it's missing a `MANIFEST.in` file.


Not related to this issue, with the patching approach you're using for this functionality, do you think that's going to cause maintenance issues over time in keeping the patched version up-to-date as changes happen in Wagtail? Note  that I'm pretty ignorant of Wagtail architecture so don't know the problems you faced to get this working.

**Comment by skirsdeda** [comment]
@tony2nite problems regarding installation should be solved by the time I publish the first release which will happen soonish if no big problems pop up.

Maintenance would be somewhat difficult with this monkey-patching approach but it's impossible to do otherwise ATM. However, I am working on a solution to make this work without any patching at all. Discussion [here](https://github.com/wagtail/wagtail/issues/3282) if you're interested. So the 1.0 release of this should not be using any patching if things go as planned.
